name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            dist
            ecosystem.config.js
            package.json
            package-lock.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: build-files

      - name: List downloaded artifact
        run: ls -la build-files

      - name: Ensure target directory exists on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /root/address-validation-service

      - name: Copy Build Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'build-files/.'
          target: '/root/address-validation-service/'
          strip_components: 1

      - name: Create .env file on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat <<'EOF' > /root/address-validation-service/.env
            PORT=${{ secrets.PORT }}
            GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}
            USPS_TOKEN_URL=${{ secrets.USPS_TOKEN_URL }}
            USPS_ADDRESS_URL=${{ secrets.USPS_ADDRESS_URL }}
            USPS_CONSUMER_KEY=${{ secrets.USPS_CONSUMER_KEY }}
            USPS_CONSUMER_SECRET=${{ secrets.USPS_CONSUMER_SECRET }}
            NODE_ENV=production
            EOF

      - name: List deployment directory contents
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 'ls -la /root/address-validation-service/'

      - name: Install Node Modules on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/address-validation-service
            npm ci
            # Rebuild native modules for current Node version
            npm rebuild || true

      - name: Start or Reload and Save PM2 Process on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/address-validation-service
            pm2 startOrReload ecosystem.config.js
            pm2 save
